(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d,e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},f;if("function"==typeof Object.setPrototypeOf)f=Object.setPrototypeOf;else{var g;a:{var h={h:!0},k={};try{k.__proto__=h;g=k.h;break a}catch(a){}g=!1}f=g?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var l=f,m=function(a,b){a.prototype=e(b.prototype);a.prototype.constructor=a;if(l)l(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var n=Object.getOwnPropertyDescriptor(b,c);n&&Object.defineProperty(a,c,n)}else a[c]=b[c]},p=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},q=p(this);var r=function(a){a=parseInt(a.getAttribute("angle"),10);isNaN(a)&&(a=0);return a},t=function(a){return a.hasAttribute("direction")?a.getAttribute("direction"):"lefttoright"};var v=function(a){if(!a.gwdIsLoaded()){var b=u(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},w=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},u=function(a){if(w(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&w(a))return a;return null};var x=function(){var a=HTMLElement.call(this)||this;a.a=null;a.frameWidth=0;a.frameHeight=0;return a};m(x,HTMLElement);d=x.prototype;d.connectedCallback=function(){v(this)};d.gwdLoad=function(){var a=this.parentElement.querySelector("canvas");a&&(this.a=a.getContext("2d"),this.frameWidth=parseInt(a.style.width,10),this.frameHeight=parseInt(a.style.height,10));this.g();var b=void 0===b?null:b;a=document.createEvent("CustomEvent");a.initCustomEvent("ready",!0,!0,b);this.dispatchEvent(a)};
d.gwdIsLoaded=function(){return!!this.a};d.renderAnimation=function(){};d.g=function(){};d.getSupportedSwipeDirection=function(){if("undefined"==typeof this.direction)return[0,0];switch(this.direction){case "lefttoright":return[1,0];case "righttoleft":return[-1,0];case "toptobottom":return[0,1];case "bottomtotop":return[0,-1];default:return[0,0]}};d.setDirection=function(){};d.resetDirection=function(){};var y=["angle","direction"],z=function(){return x.call(this)||this};m(z,x);d=z.prototype;d.connectedCallback=function(){this.f=t(this);var a=r(this);this.c=Math.tan(89<a||-89>a?0:a*Math.PI/180);v(this)};d.attributeChangedCallback=function(a){switch(a){case "direction":this.f=t(this);this.g();break;case "angle":a=r(this),this.c=Math.tan(89<a||-89>a?0:a*Math.PI/180),this.g()}};
d.g=function(){this.b="toptobottom"==this.f||"bottomtotop"==this.f?Math.abs(this.frameWidth*this.c):Math.abs(this.frameHeight*this.c)};d.setDirection=function(a){this.f=a};d.resetDirection=function(){this.f=t(this)};
d.renderAnimation=function(a,b,c){this.a.clearRect(0,0,this.frameWidth,this.frameHeight);this.a.drawImage(a,0,0,this.frameWidth,this.frameHeight);this.a.save();this.a.beginPath();if(0==this.c)switch(this.f){case "righttoleft":this.a.rect((1-c)*this.frameWidth,0,this.frameWidth*c,this.frameHeight);break;case "toptobottom":this.a.rect(0,0,this.frameWidth,this.frameHeight*c);break;case "bottomtotop":this.a.rect(0,(1-c)*this.frameHeight,this.frameWidth,this.frameHeight*c);break;default:this.a.rect(0,
0,this.frameWidth*c,this.frameHeight)}else switch(this.f){case "toptobottom":a=c*(this.frameHeight+this.b);0<this.c?(this.a.lineTo(0,a),this.a.lineTo(this.frameWidth,a-this.b)):(this.a.lineTo(0,a-this.b),this.a.lineTo(this.frameWidth,a));this.a.lineTo(this.frameWidth,0);this.a.lineTo(0,0);break;case "bottomtotop":a=(1-c)*(this.frameHeight+this.b);0<this.c?(this.a.lineTo(0,a),this.a.lineTo(this.frameWidth,a-this.b)):(this.a.lineTo(0,a-this.b),this.a.lineTo(this.frameWidth,a));this.a.lineTo(this.frameWidth,
this.frameHeight);this.a.lineTo(0,this.frameHeight);break;case "righttoleft":a=(1-c)*(this.frameWidth+this.b);0<this.c?(this.a.lineTo(a,0),this.a.lineTo(a-this.b,this.frameHeight)):(this.a.lineTo(a-this.b,0),this.a.lineTo(a,this.frameHeight));this.a.lineTo(this.frameWidth,this.frameHeight);this.a.lineTo(this.frameWidth,0);break;default:a=c*(this.frameWidth+this.b),0<this.c?(this.a.lineTo(a,0),this.a.lineTo(a-this.b,this.frameHeight)):(this.a.lineTo(a-this.b,0),this.a.lineTo(a,this.frameHeight)),this.a.lineTo(0,
this.frameHeight),this.a.lineTo(0,0)}this.a.clip();this.a.clearRect(0,0,this.frameWidth,this.frameHeight);this.a.drawImage(b,0,0,this.frameWidth,this.frameHeight);this.a.restore()};q.Object.defineProperties(z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return y}}});customElements.define("gwd-wipe",z);}).call(this);
